kind: pipeline
type: docker
name: default

steps:      
  - name: kops_infra
    image: turik207/kops:1.23.2.7
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    commands:
      - export $keyid
      - export $key
      - kops create cluster --name cluster.turali7v.click --zones eu-central-1a --state s3://kube-tismov-bt --yes
      - sleep 30
      - kops validate cluster --state=s3://kube-tismov-bt --name=cluster.turali7v.click --wait 10m
      - cat $HOME/.kube/config
      - cat $HOME/.kube/config > config
      
  - name: istioctl
    image: turik207/istio:1.14
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    commands:
      - export $keyid
      - export $key
      - export KUBECONFIG=./config
      - istioctl version
      - istioctl install -y
      
  - name: kubectl
    image: turik207/kubectl:1.23
    environment:
      keyid:
        from_secret: keyid
      key:
        from_secret: key
    commands:
      - export $keyid
      - export $key
      - export KUBECONFIG=./config
      - kubectl label namespace default istio-injection=enabled
      - kubectl get nodes
      - kubectl get namespaces

  - name: copy configfile s3
    image: amazon/aws-cli
    environment:
      accesskey:
        from_secret: seckeyid
      secretkey:
        from_secret: seckey
    commands:
      - export $accesskey
      - export $secretkey
      - aws --version
      - aws s3 cp config s3://k8s-kubeconfig-i7v/